HotelRecruitment/HotelRecruitment/Models/JobSeeker.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class JobSeeker
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Typeofposition { get; set; }
        public string workplace { get; set; }
        public string Position { get; set; }
        public string CV { get; set; }
        public string Feedback { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<bool> IsInterview { get; set; }
        
     
        HttpPostedFileBase File { get; set; }

    }
}

HotelRecruitment/HotelRecruitment/Controllers/JobSeekerController.cs
using DAL;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelRecruitment.Controllers
{
    public class JobSeekerController : Controller
    {
        HotelManagementEntities dbContext = new HotelManagementEntities();
        //
        // GET: /JobSeeker/
        public ActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registration(JobSeeker model, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    DAL.JobSeeker jobSeeker = new DAL.JobSeeker();

                    jobSeeker.Name = model.Name;

                    jobSeeker.Email = model.Email;
                    jobSeeker.Mobile = model.Mobile;
                    jobSeeker.Salary = model.Salary;
                    jobSeeker.Typeofposition = model.Typeofposition;
                    jobSeeker.Position = model.Position;
                    jobSeeker.workplace = model.workplace;
                    jobSeeker.IsActive = false;
                    jobSeeker.IsDeleted = false;
                    jobSeeker.CreatedOn = DateTime.Now;


                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);

                        string fileExtension = Path.GetExtension(fileName);

                        if (fileExtension != ".pdf")
                        {
                            return View();
                        }
                        fileName = DateTime.Now.Ticks + fileName;

                        var path = Path.Combine(Server.MapPath("~/Content/Upload/CV/"), fileName);
                        file.SaveAs(path);
                        jobSeeker.CV = fileName.ToString();
                    }

                    dbContext.JobSeekers.Add(jobSeeker);
                    dbContext.SaveChanges();

                }

                catch (DbEntityValidationException e)
                {

                    foreach (var eve in e.EntityValidationErrors)
                    {
                        Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                            eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        foreach (var ve in eve.ValidationErrors)
                        {
                            Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                                ve.PropertyName, ve.ErrorMessage);
                        }
                    }
                    throw e;

                }

            }

            return RedirectToAction("Thankyou");
        }

        public ActionResult Update(int Id)
        {

            DAL.JobSeeker jobSeeker = dbContext.JobSeekers.Where(x => x.Id == Id).FirstOrDefault();
            Model.JobSeeker model = new Model.JobSeeker();
            model.Id = jobSeeker.Id;
            model.Name = jobSeeker.Name;
            model.Mobile = jobSeeker.Mobile;
            model.Email = jobSeeker.Email;
            model.Salary = jobSeeker.Salary;
            model.Typeofposition = jobSeeker.Typeofposition;
            model.workplace = jobSeeker.workplace;
            model.Position = jobSeeker.Position;
            model.CreatedOn = jobSeeker.CreatedOn;
            model.CV = jobSeeker.CV;
            model.IsActive = jobSeeker.IsActive;
            model.IsDeleted = jobSeeker.IsDeleted;

            return View(model);
        }
        [HttpPost]
        public ActionResult Update(JobSeeker model, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    //DAL.JobSeeker jobSeeker = new DAL.JobSeeker();
                    //jobSeeker.Name = model.Name;
                    //jobSeeker.Email = model.Email;
                    //jobSeeker.Mobile = model.Mobile;
                    //jobSeeker.Salary = model.Salary;
                    //jobSeeker.Typeofposition = model.Typeofposition;
                    //jobSeeker.Position = model.Position;
                    //jobSeeker.workplace = model.workplace;
                    //jobSeeker.IsActive = true;
                    //jobSeeker.IsDeleted = false;
                    //jobSeeker.CreatedOn = DateTime.Now;

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);

                        string fileExtension = Path.GetExtension(fileName);

                        if (fileExtension != ".pdf")
                        {
                            return View();
                        }
                        fileName = DateTime.Now.Ticks + fileName;

                        var path = Path.Combine(Server.MapPath("~/Content/Upload/CV/"), fileName);
                        file.SaveAs(path);
                        model.CV = fileName.ToString();
                    }


                    dbContext.Entry(model).State = EntityState.Modified;
                    dbContext.SaveChanges();

                }

                catch (Exception ex)
                {

                    throw ex;

                    //foreach (var eve in e.EntityValidationErrors)
                    //{
                    //    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                    //        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    //    foreach (var ve in eve.ValidationErrors)
                    //    {
                    //        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                    //            ve.PropertyName, ve.ErrorMessage);
                    //    }
                    //}
                    //throw e;

                }

            } return RedirectToAction("Thankyou");
        }

        public ActionResult List()
        {
            return View();
            //return View(dbContext.JobSeekers.Where(x => x.IsDeleted == false).ToList().OrderByDescending(x => x.CreatedOn));
        }
        public ActionResult Thankyou()
        {
            return View();
        }
        public bool UpdateRating(int Rating, string Feedback, int JobSeekerId, bool IsInterview, bool IsActive)
        {

            var jobSeeker = dbContext.JobSeekers.Where(x => x.Id == JobSeekerId).FirstOrDefault();

            jobSeeker.Rating = Convert.ToInt32(Rating);
            jobSeeker.Feedback = Feedback;
            jobSeeker.IsInterview = IsInterview;
            jobSeeker.IsActive = IsActive;

            dbContext.SaveChanges();

            return true;
        }

        public ActionResult Index()
        {
            return View();
        }

    }
}

HotelRecruitment/HotelRecruitment/Views/JobSeeker/Index.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>landing page for job seeker</h2>

HotelRecruitment/HotelRecruitment/Views/JobSeeker/List.cshtml
@model IEnumerable<DAL.JobSeeker>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="/Scripts/angular.min.js"></script>
<script src="/Scripts/JobSeeker/Module.js"></script>
<script src="/Scripts/JobSeeker/Service.js"></script>
<script src="/Scripts/JobSeeker/Controller.js"></script>
<div ng-controller="myCntrl">
    <div class="heading_part">
        <div class="center_container"><h2>Dashboard</h2></div><!---center_container--->
    </div><!---heading_part--->

    <div class="header_fullparts">
        <div class="center_container">
            <div class="col-xs-6 col-sm-3 parts_fullparts dashboard_parts">
                <h2>{{employees.length}}</h2>
                <p>Number of CVS</p>
            </div>

            <div class="col-xs-6 col-sm-3 parts_fullparts dashboard_parts">
                <h2>5 <!--span><img src="images/email.png"/></span--></h2>
                <p>Number of Jobs</p>
            </div>

            <div class="col-xs-6 col-sm-3 parts_fullparts dashboard_parts">
                <h2>2 <!--span><img src="images/positon.png"/></span--></h2>
                <p>Sales</p>
            </div>

            <div class="col-xs-6 col-sm-3 parts_fullparts dashboard_parts">
                <h2>3 <!--span><img src="images/LAST.png"/></span--></h2>
                <p>Outstanding</p>
            </div>
        </div><!---center_container--->
    </div> <!---header_fullparts--->



    <div class="main_box_pernolinfo">
        <div class="col-xs-12 col-sm-6 cv_box">
            <h1 class="c_v">CV</h1>

            <table class="table-responsive cv_table">

                <tr style="background: #CCCCCC;">
                    <th class="dropdown">Name</th>
                    <th class="dropdown">Type</th>
                    <th class="dropdown">Salary</th>
                    <th class="dropdown">CV</th>
                    <th class="dropdown">Interveiw</th>
                    <th class="dropdown">Rating</th>
                </tr>
                <tr ng-repeat="employee in employees">
                    <td style="cursor:pointer;" ng-click="editEmployee(employee)">{{employee.Name}}</td>
                    <td>{{employee.Typeofposition}}</td>
                    <td>{{employee.Salary}}</td>
                    <td><a target="_blank" href="~/Content/Upload/Cv/{{employee.CV}}"><img style="width:18px;" src="../content/images/pdf.png" /></a></td>
                    <td><input onclick="return false" ng-checked="employee.IsInterview" ng-model="employee.IsInterview" name="chkJobSeeker" id="{{employee.Id}}" type="checkbox" /></td>
                    <td>{{employee.Rating}}</td>
                </tr>
            </table>
        </div>

        <div class="col-xs-12 col-sm-6 testimonial_part drill_down">
            <h1 class="c_v">CV Drilldown</h1>
            <div class="col-xs-12 col-sm-12 text_drilldown">
                <b>{{Name}}</b>
                <p>Imformation that is collected.</p>
                <p>Lorem Ipsum doller to set the content tin for the togather to set timing the program to epsum contest to set.</p>
                <input type="checkbox" ng-model=IsActive ng-checked="{{IsActive}}" name="IsActive" /> Is Active ?<br />
                <input type="checkbox" ng-model=IsInterview ng-checked="{{IsInterview}}" name="IsInterview" /> Is Interview ?

                <p><textarea ng-model="Feedback" placeholder="Multitext"></textarea></p>
                <p>
                    <div class="form-group">
                        <div style="float:left;width:200px;">
                            <input type="submit" value="Update" class="btn btn-primary" ng-click="UpdateEmployee()" />
                        </div>
                    </div>
                </p>
                <p class="text-right">
                    <select data-ng-options="o.name for o in options" data-ng-model="selectedOption"></select>
                </p>
            </div>
        </div>
    </div>  <!---main_box_pernolinfo--->
</div>

HotelRecruitment/HotelRecruitment/Views/JobSeeker/Registration.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />

<script src="/Scripts/angular.min.js"></script>
<script src="/Scripts/JobSeeker/Module.js"></script>
<script src="/Scripts/JobSeeker/Service.js"></script>
<script src="/Scripts/JobSeeker/Controller.js"></script>

<script type="text/javascript">

    $(document).ready(function () {

        $('form').submit(function () {

            if ($(this).valid()) {

                setTimeout(Redirect, 1000);

            }
        });

    });

    function Redirect() {
        window.location = 'http://localhost:23758/jobseeker/Thankyou';
    }
</script>

<div ng-controller="myCntrl">

    <form name="registerform" action="/api/jobseekerregistrationservice" enctype="multipart/form-data" method="post">

        <div class="heading_part">
            <div class="center_container"><h2>Submit Your CV</h2></div>
        </div>

        <div class="header_fullparts">
            <div class="center_container">
                <div class="col-xs-6 col-sm-3 parts_fullparts">
                    <h2>Name</h2>
                    <input type="text" ng-model="Name" name="Name" placeholder="Enter your name" required />
                </div>

                <div class="col-xs-6 col-sm-3 parts_fullparts">
                    <h2>E-mail</h2>
                    <input type="email" ng-model="Email" name="Email" placeholder="Email Address" ng-required="true" />

                </div>

                <div class="col-xs-6 col-sm-3 parts_fullparts">
                    <h2>Position</h2>
                    <input type="text" ng-model="Position" name="Position" placeholder="Current position" />
                </div>

                <div class="col-xs-6 col-sm-3 parts_fullparts">
                    <h2>CV</h2>
                    <input type="file" name="File" accept=".pdf" style="margin-left: -2px; border: 0;" />
                </div>
            </div>
        </div>

        <div class="persnol_imformation">
            <div class="center_container">
                <h1>Personal Imformation</h1>
            </div>
        </div>

        <div class="main_box_pernolinfo">
            <div class="col-xs-12 col-sm-6 text_boxes">
                <p>
                    <input type="text" ng-model="Mobile" name="Mobile" placeholder="Mobile phone number" ng-required="true" />
                </p>
                <p>
                    <input type="text" ng-model="Salary" name="Salary" placeholder="Current salary" />
                </p>
                <p>
                    <textarea rows="3" ng-model="Typeofposition" name="Typeofposition" placeholder="What type of Position Are you looking For?"></textarea>
                </p>
                <p>
                    <textarea rows="3" ng-model="workplace" name="workplace" placeholder="Where you you want to work? in Sri Lanka or somewhere else in the world?"></textarea>
                </p>
                <div class="form-group">
                    <div>
                        <input type="submit" value="Submit" class="btn btn-primary" />
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 testimonial_part">
                <div class="col-xs-6 col-sm-7 text_testimonial">
                    <p>Hi</p>
                    <p>
                        Upload your CV to my website and I will do my best to find a new position for you. I can not promise anything, but I will give you feedback during the process. I suggest to check your email or keep your mobile with you.
                    </p>
                    <p class="text-right"><img src="~/content/images/IMG_24052016_114029.png" /></p>
                </div>
                <div class="col-xs-6 col-sm-5 img_testimonial">
                    <img class="img-circle" src="~/content/images/lady.png" />
                </div>
            </div>
        </div>

    </form>
</div>

HotelRecruitment/HotelRecruitment/Views/JobSeeker/Thankyou.cshtml
@{
    ViewBag.Title = "Thankyou";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<h1>
    Thankyou for submitting your information
</h1>

HotelRecruitment/HotelRecruitment/Views/JobSeeker/Update.cshtml
@model Model.JobSeeker

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="heading_part">
    <div class="center_container"><h2>Update Your CV</h2></div><!---center_container--->
</div>

    @using (Html.BeginForm("Update", "JobSeeker", FormMethod.Post, new { @class = "form-vertical", role = "form1", @autocomplete = "off", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CreatedOn)
        @Html.HiddenFor(model => model.CV)
        @Html.HiddenFor(model => model.IsActive)
        @Html.HiddenFor(model => model.IsDeleted)

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="header_fullparts">
            <div class="center_container">
                <div class="col-xs-6 col-sm-3 parts_fullparts">
                    <h2>Name</h2>
                    @Html.TextBoxFor(model => model.Name, new { @placeholder = "Enter your name" })
                </div>

                <div class="col-xs-6 col-sm-3 parts_fullparts">
                    <h2>Email</h2>
                    @Html.TextBoxFor(model => model.Email, new { @placeholder = "Email Address" })
                </div>

                <div class="col-xs-6 col-sm-3 parts_fullparts">
                    <h2>Position</h2>
                    @Html.TextBoxFor(model => model.Position, new { @placeholder = "Current position" })
                </div>

                <div class="col-xs-6 col-sm-3 parts_fullparts">
                    <h2>CV</h2>
                    <input type="file" name="file" class="file" style="margin-left:-2px;border:none;">
                </div>
            </div>
        </div>

        <div class="persnol_imformation">
            <div class="center_container">
                <h1>Persnol Imformation</h1>
            </div>
        </div> 

        <div class="main_box_pernolinfo">
            <div class="col-xs-12 col-sm-6 text_boxes">

                <p>@Html.TextBoxFor(model => model.Mobile, new { @placeholder = "Mobile phone number" })</p>
                <p>@Html.TextBoxFor(model => model.Salary, new { @placeholder = "Current salary" })</p>
                <p>@Html.TextAreaFor(model => model.Typeofposition, new { @placeholder = "What type of Position Are you looking For?" })</p>
                <p>@Html.TextAreaFor(model => model.workplace, new { @placeholder = "Where you you want to work? in Sri Lanka or somewhere else in the world?" })</p>
                <div class="form-group">
                    <div>
                        <input type="submit" value="Update" class="btn btn-primary" />
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 testimonial_part">
                <div class="col-xs-6 col-sm-7 text_testimonial">
                    <p>Hi</p>
                    <p>
                        Upload your CV to my website and I will do my best to find a new position for you. I can not promise anything, but I will give you feedback during the process. I suggest to check your email or keep your mobile with you.
                    </p>
                    <p class="text-right"><img src="~/content/images/IMG_24052016_114029.png" /></p>
                </div>
                <div class="col-xs-6 col-sm-5 img_testimonial">
                    <img class="img-circle" src="~/content/images/lady.png" />
                </div>
            </div>
        </div>
        
        
    }